[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = "warexlogistics.up.railway.app"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
base = "dark"
